---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2022/12/13 20:49
---
print(true and 5)
print(nil and hello)
print(false and 2)
print(4 and 5)
print(false or nil)
print(arg[0])
print(type(nil) ==nil)
print(false or 12)