---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2022/12/16 14:57
---
local a,b=2,3

print(a+b)
print("----------")
print("123"+b)
print("----------")
print(a-b)
print("----------")
print("123"-b)
print("----------")
print(a*b)
print("----------")
print(a/b)
print("----------")
print(a%b)
print("----------")
print(a^b)
print("----------")
print(a>b)
print("----------")
print(a<b)
print("----------")
print(a==b)
print("----------")
print(a~=b)
print("----------")