---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2023/1/4 20:51
---
Demo={name={id={score=100}}}

print(Demo.name.id.score)
Demo.name.id=nil;
--print(Demo.name.id.score)
test=(((Demo or {}).name or {}).id or {}).score
print(test)