---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2022/12/17 16:42
---
print("--------函数--------")
function f()
    print("简单函数")
end
f()--调用函数
print("--------无参数无返回值--------")
a=function()
    print("无参数类型")
end
a()
print("--------有参数--------")
function f1(num)
    print("传入的参数为"..num)
end
f1(9)
print("--------有返回值--------")
function f2(num)
    return num
end
temp=f2(5)
print(temp)
print("--------函数的类型--------")
f=function ()
    print("Hello World !")
end
print(type(f))
print("--------变长参数--------")
function f3(...)
    temp={...}
    for i = 1, #temp do
        print(temp[i])
    end
end
f3(1,"111",3)
print("--------函数嵌套--------")
function f4(a)
    return function(b)
        print(a+b)
    end
end
f=f4(2)
f(3)