---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2023/1/4 21:57
---
strs=" "
t={}
for i = 1, 10 do
    table.insert(t,i)
end
print(#t)
s=table.concat(t)
print(s)