---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2022/12/13 15:48
---
function fact (n)
    if n == 0
    then return 1
    else
        return n * fact(n - 1)
    end
end
print("请输入一个数字:")

a = io.read("*n") -- reads a number print(fact(a))
print(fact(a))