---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2022/12/26 14:36
---
print("--------构建字典--------")
a={["name"]="小明",["age"]=18,["id"]=1001}
print(a.name)
print(a.age)
print(a.id)
--a={["home"]=1002}

for i, v in pairs(a) do
    print(i,v)
end