---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2022/12/26 15:34
---
print("--------类--------")

student={
    age=10,
    name="小明",
    id=1001,

    learn=function()
        print("好好学习")
    end,
    Up=function()
        print("天天向上")
    end,
    test03=function(t)
        print("我的年龄是"..t.age)
    end
    }
student.test01=function()
    print("test01")
end

function student.test02()
    print("test02")
end
function student:test04()
    print(self.name)
end

print(student.learn())
print(student.Up())
print(student.test01())
print(student.test02())
print(student:test03())
print(student:test04())
for i, v in pairs(_G) do
    print(i,v)
end