---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2022/12/17 22:18
---
print("--------复杂数据类型--------")
print("--------数组--------")
array={1,2,nil,3,4,"123",true,nil}
for i = 1, #array do
    print(array[i])
end
--打印数组长度时 空忽略不计
print(#array)
print("--------二维数组--------")
array={{1,2,3},{4,5,6}}
for i = 1, #array do
    newArray=array[i]
    for j = 1,#newArray do
        print(array[i][j])
    end
end
print("--------自定义索引--------")
array={[0]=1,2,3,[-1]=4}
print(array[0])
