---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2022/12/16 14:27
---
print(type(123))
print(type("abc"))
print(type('123'))
print(type(nil))
print(type(false))
print("123".."456")