---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28594.
--- DateTime: 2022/12/15 14:45
---
-- The eight-queen program

N = 8 -- board size 棋盘大小

-- 检查位置(n,c)是否是一个安全的位置，a是数组
function isplaceok (a, n, c)
    for i = 1, n - 1 do        -- 对每一个已经摆放好的列
        if (a[i] == c) or          -- 同一列
                (a[i] - i == c - n) or     -- 同斜线
                (a[i] + i == c + n) then   -- 同斜线
            return false   -- 位置是可被攻击到的
        end
    end
    return true   -- 位置是安全的
end

-- 打印棋盘
function printsolution (a)
    for i = 1, N do  -- 循环每一行
        for j = 1, N do -- 循环每一列
            --打印X和横线
            io.write(a[i] == j and "X" or "-", " ")
        end
        io.write("\n")
    end
    io.write("\n")
end

-- 添加一个棋子，n代表第几个棋子
function addqueen (a, n)
    if n > N then       -- 已经完成了最后一列
        printsolution(a)
    else                -- 尝试放第N个皇后
        for c = 1, N do
            if isplaceok(a, n, c) then
                a[n] = c           -- 将第N个皇后放在第c行
                addqueen(a, n + 1)
            end
        end
    end
end

-- 启动程序
addqueen({}, 1)
